- name: install supervisor
  apt:
    name: "supervisor={{ supervisor_version }}*"
    state: present
    force: yes

- name: modify supervisord.conf
  template:
    src: supervisord.conf
    dest: /etc/supervisor/supervisord.conf
    owner: root
    group: root
    mode: 0644
  notify: restart supervisor

- include: clashmail.yml

- name: supervisor is enabled
  service:
    name: supervisor
    state: started
    enabled: yes
