- name: modify directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ supervisor_path_home }}"
    - "{{ supervisor_path_conf }}"
    - "{{ supervisor_path_log }}"

- name: pip install supervisord
  pip:
    name: supervisor
    version: "{{ supervisor_version }}"
    virtualenv: "{{ supervisor_path_venv }}"

- name: pip install superlance (clashmail)
  pip:
    name: superlance
    virtualenv: "{{ supervisor_path_venv }}"

- name: modify init
  template:
    src: init
    dest: /etc/init.d/supervisord
    owner: root
    group: root
    mode: 0755

- name: modify supervisord.conf
  template:
    src: supervisord.conf
    dest: "{{ supervisor_path_home }}/supervisord.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart supervisord

- name: modify sub config
  template:
    src: "conf.d/{{ item }}"
    dest: "{{ supervisor_path_conf }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - crashmail.conf

- name: supervisord is enabled
  service:
    name: supervisord
    state: started
    enabled: yes

- name: modify logrotate conf
  template:
    src: logrotate
    dest: /etc/logrotate.d/supervisord
    owner: root
    group: root
    mode: 0644
